### ISSUE TITLE
Research Direction: Finding optimal number of segments

### ISSUE THREAD

**Issue by lamtung16** [lamtung16/ML_ChangepointDetection#13]
@tdhock,
In changepoint detection, the Dynamic Programming (DP) algorithm offers two approaches to regulate the number of changepoints:
1. Setting an optimal penalty $\lambda$
2. Setting an optimal number of segments

I have been working on approach 1, which involves interval regression, utilizing MLP, RNN, .... 

Do you think exploring approach 2 could be a promising direction? In this approach, we could apply models (such as RNNs) directly to the raw sequence to predict the optimal number of segments.

**Comment by tdhock** [comment]
no I don't think this is a good idea. approach 1 is always more efficient, see my paper 
![Hocking2022jss](https://github.com/user-attachments/assets/4b5bd985-ec0a-4b47-bde9-55add055b2fd)
https://www.jstatsoft.org/article/view/v101i10
