### ISSUE TITLE
squared hinge versus square loss for training

### ISSUE THREAD

**Issue by tdhock** [lamtung16/ML_ChangepointDetection#5]
hi @lamtung16 here is a result figure showing that linear model trained by minimizing square loss (lm.2) is about the same as linear model trained by minimizing squared hinge loss (linear.2), can you please create a similar figure using your code, for debugging purposes?
![Untitled](https://github.com/lamtung16/ML_ChangepointDetection/assets/932850/0b6ff403-5078-41ea-b3dc-b5ae87ee8b35)

**Comment by lamtung16** [comment]
Hi Dr. @tdhock, this is my figure, I used different shapes for my results and paper's results, just for differentiation. I have exactly the same results in BIC and constant, slightly different in linear model.
![image](https://github.com/lamtung16/ML_ChangepointDetection/assets/46878211/58461ed4-a071-4b3f-aa0f-dee89225d788)

**Comment by tdhock** [comment]
that is good progress, thanks for sharing. now can you please add all of your other variants to this same figure?

**Comment by lamtung16** [comment]
I added them into the figure
![image](https://github.com/lamtung16/ML_ChangepointDetection/assets/46878211/8d687bf7-88ae-4884-b4d4-350a37cb8a12)
