### ISSUE TITLE
paper revisions

### ISSUE THREAD

**Issue by tdhock** [lamtung16/ML_ChangepointDetection#9]
before submitting https://arxiv.org/pdf/2408.00856 for peer review, please do the following.

add citation to https://deepcharles.github.io/files/TOV-EUSIPCO-17.pdf which is similar to your approach.

increase figure text size so it is about the same as caption text size. below is too small.
![image](https://github.com/user-attachments/assets/d93ec3c0-c761-4911-8738-f8b0dd467855)

below table text is also small.
would be better if you could remove "mlp." to save space.
![image](https://github.com/user-attachments/assets/31860487-7070-44ad-b9ae-31d7374249fb)

below figure text too small 
![image](https://github.com/user-attachments/assets/25a7622c-88d0-4090-a83e-e1e74ce38dab)

below figure text too small 
![image](https://github.com/user-attachments/assets/492c3767-ca13-4d36-95bc-586b1e0b1c4b)

below figure text too small
![image](https://github.com/user-attachments/assets/4df219ff-b1c5-43b0-87d7-d1ea4b26f264)

below figure text is almost too small (OK for peer review, but would be better just slightly larger)
![image](https://github.com/user-attachments/assets/4d6eb008-14fa-4d5f-a21f-62206af990b4)

**Comment by lamtung16** [comment]
I updated the paper, when you have time, please take a look and give me some feedbacks
[Paper_ver2.pdf](https://github.com/user-attachments/files/16563800/Paper_ver2.pdf)

**Comment by tdhock** [comment]
Fig 7 is better but axis text is still very small, and neighbors are too close together (for example 256 and 512)
maybe fix  by omitting every other text label: show only 128,  512 instead of 128, 256, 512.
![image](https://github.com/user-attachments/assets/fee2a5bb-c35c-4493-9f69-70170948ba3c)

**Comment by tdhock** [comment]
new table 2 is good.

Fig 6 text size is good now but x axis text may be confusing to read, because some text 96, 99, 74, is very close to edge of panel.
![image](https://github.com/user-attachments/assets/245d3dc8-7be2-4dec-b786-0afea220cffa)

could be improved by adding horizontal space between panels.

**Comment by tdhock** [comment]
revised fig 3 is excellent, great work !

in new Fig 5 is looks like x/y axis title text is bigger which is good.
but it looks like tick mark text is smaller which is bad.
![image](https://github.com/user-attachments/assets/c6d562ee-bf21-4ac3-a4c2-1cc4c145431f)
please fix by increasing tick mark text.

**Comment by lamtung16** [comment]
Here is my updates:
- Fig 7: instead of showing in x-axis 2, 4, 8, 16, 32, 64, 128, 256, 512, only showing 2, 8, 32, 128, 512.
- Fig 6: update the position of 3 vertical lines, so the figure is more clear.
- Fig 5: I increased the size of tick mark text. (I still think the text in Fig 5 is small, but so far that is the best I can do, maybe I can replace the text to make them shorter, such as removing 'feature=', 'output=')

Please take a look: 
[paper_ver2.pdf](https://github.com/user-attachments/files/16574247/paper_ver2.pdf)

**Comment by tdhock** [comment]
For Table 2 instead of writing "0" you could just leave the entry blank, which would provide greater visual emphasis between 0 and non-zero.
new fig 7 looks great.
New fig 6 looks great.
new fig 5 looks great.
overall great work, please re-read one last time and then submit for peer review.

**Comment by lamtung16** [comment]
Ok will do, thank you for your help 🙂

**Comment by lamtung16** [comment]
I updated my paper and about to submit for peer review, can you take a look and give me some feedbacks
[paper_ver3.pdf](https://github.com/user-attachments/files/17157510/paper_ver3.pdf)

**Comment by tdhock** [comment]
looks good overall. Fig 4 is new right? i like it.
please submit
